// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateCapsule(item: $models.Capsule): $CancellablePromise<$models.Capsule> {
    return $Call.ByID(3134107613, item).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteCapsule(id: number): $CancellablePromise<void> {
    return $Call.ByID(566933480, id);
}

export function GetCapsules(page: number, perPage: number): $CancellablePromise<$models.CapsulesResponse> {
    return $Call.ByID(1062045482, page, perPage).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateCapsule(id: number, item: $models.Capsule): $CancellablePromise<$models.Capsule> {
    return $Call.ByID(852987346, id, item).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Capsule.createFrom;
const $$createType1 = $models.CapsulesResponse.createFrom;
