// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CapsuleService from "./capsuleservice.js";
export {
    CapsuleService
};

export {
    Capsule,
    CapsulesResponse
} from "./models.js";
