// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Capsule {
    "id": number;
    "createdAt": string;
    "contentText": string;
    "audioPath": string | null;
    "attachmentPaths"?: string | null;
    "classification": string;
    "isWithSchedule": number;
    "scheduleIcon"?: string | null;
    "scheduleContentText"?: string | null;
    "scheduleStartAt"?: string | null;
    "scheduleEndAt"?: string | null;
    "scheduleStatus"?: string | null;
    "scheduleDeadline"?: string | null;
    "alarmClocks"?: string | null;

    /** Creates a new Capsule instance. */
    constructor($$source: Partial<Capsule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("contentText" in $$source)) {
            this["contentText"] = "";
        }
        if (!("audioPath" in $$source)) {
            this["audioPath"] = null;
        }
        if (!("classification" in $$source)) {
            this["classification"] = "";
        }
        if (!("isWithSchedule" in $$source)) {
            this["isWithSchedule"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capsule instance from a string or object.
     */
    static createFrom($$source: any = {}): Capsule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capsule($$parsedSource as Partial<Capsule>);
    }
}

export class CapsulesResponse {
    "data": Capsule[];
    "total": number;
    "page": number;
    "perPage": number;

    /** Creates a new CapsulesResponse instance. */
    constructor($$source: Partial<CapsulesResponse> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("perPage" in $$source)) {
            this["perPage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapsulesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CapsulesResponse {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new CapsulesResponse($$parsedSource as Partial<CapsulesResponse>);
    }
}

// Private type creation functions
const $$createType0 = Capsule.createFrom;
const $$createType1 = $Create.Array($$createType0);
