// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCapsule(arg1) {
  return window['go']['main']['App']['CreateCapsule'](arg1);
}

export function DeleteCapsule(arg1) {
  return window['go']['main']['App']['DeleteCapsule'](arg1);
}

export function GetCapsules(arg1, arg2) {
  return window['go']['main']['App']['GetCapsules'](arg1, arg2);
}

export function UpdateCapsule(arg1, arg2) {
  return window['go']['main']['App']['UpdateCapsule'](arg1, arg2);
}
