// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCapsule(arg1:main.Capsule):Promise<main.Capsule>;

export function DeleteCapsule(arg1:number):Promise<void>;

export function GetCapsules(arg1:number,arg2:number):Promise<main.CapsulesResponse>;

export function UpdateCapsule(arg1:number,arg2:main.Capsule):Promise<main.Capsule>;
